build:
	gcc -Wall -Werror -Wextra s21_cat.c s21_main_cat.c -o s21_cat

base:
	./s21_cat ../data/test.txt ../data/test2.txt

N:
	./s21_cat -n ../data/test.txt ../data/test2.txt

B:
	./s21_cat -n -b -n ../data/test.txt ../data/test2.txt

E:
	./s21_cat -e ../data/test.txt ../data/test2.txt

NE:
	./s21_cat -n -e ../data/test.txt ../data/test2.txt

BE:
	./s21_cat -b -e ../data/test.txt ../data/test2.txt
	
T:
	./s21_cat -t ../data/test.txt ../data/test2.txt
