build:
	gcc -Wall -Werror -Wextra s21_cat.c s21_main_cat.c -o s21_cat

base:
	./s21_cat ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt

N:
	./s21_cat -n ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt

B:
	./s21_cat -n -b -n ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt

E:
	./s21_cat -e ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt

NE:
	./s21_cat -n -e ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt

BE:
	./s21_cat -b -e ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt
	
T:
	./s21_cat -b -e ../../data-samples/testSample1.txt ../../data-samples/testSample3.txt ../../data-samples/testSample2.txt
